### ISSUE TITLE
the table "contract_info" is Empty

### ISSUE THREAD

**Issue by zhidongfeifan** [WeBankBlockchain/Data-Export#31]
Hello，I refer to the official demo ：
https://github.com/WeBankBlockchain/Data-Export-Demo 
and export all the transaction data on the chain, but I find that the data in the table **"contract_info"** is empty, although other tables can be synchronized normally. 
As a result, the name, ABI and bin values of the contract cannot be obtained.
Can it be solved?

**Comment by wangyue168git** [comment]
Hi,
we need to configure the contract of abi and bin information, contract_info will have data, reference: https://github.com/WeBankBlockchain/Data-Export-Demo/blob/main/src/main/java/com/webank/blockchain/data/export/sdk/demo/ContractDataExportDemo.java

The ABI and BIN of the contract can be obtained by compiling Java files from the Fisco console or the SDK
