### ISSUE TITLE
methodBO（）里的contract_address字段一直是0

### ISSUE THREAD

**Issue by masonhunk** [WeBankBlockchain/Data-Export#41]
这个字段如果表示合约调用的地址，那么不应该是0.

![image](https://user-images.githubusercontent.com/6778136/131651605-c519e253-32e0-4e6e-805a-09b52f01d48f.png)

改字段直接取自TransactionReceipt的contract_address，contract_address字段表示合约部署生成的地址，而不是合约执行的地址，在非合约部署交易情况下，该字段一直是0.
如果想取合约执行的地址，应该取to字段。

**Comment by saiwg** [comment]
这个解决了吗？

**Comment by dalaocu** [comment]
> 

由于历史原因，这个字段需要和SDK保持兼容。
