### ISSUE TITLE
PrepareTaskJob类中并没有创建数据库连接步骤，导致多活部署无法正常运行

### ISSUE THREAD

**Issue by xxmlovezw** [WeBankBlockchain/Data-Export#51]
**原代码**
public PrepareTaskJob(DataExportContext context) {
        this.context = context;
        this.dataPersistenceManager = DataPersistenceManager.create(context);
        try{
            this.context.setDecoder(new TransactionDecoderService(context.getClient().getCryptoSuite()));
            dataPersistenceManager.saveContractInfo();
        }catch (Exception e) {
            log.error("save Contract Info, {}", e.getMessage());
        }
        mapsInfo = ContractParser.initContractMaps(context.getConfig().getContractInfoList());
        ExportConstant.setCurrentContext(context);
        DataPersistenceManager.setCurrentManager(dataPersistenceManager);
        ContractConstants.setCurrentContractMaps(mapsInfo);
        dataPersistenceManager.buildDataStore();
    }
**修改后多活部署可以运行代码**
public PrepareTaskJob(DataExportContext context) {
        this.context = context;
        this.dataPersistenceManager = DataPersistenceManager.create(context);
        DataPersistenceManager.setCurrentManager(dataPersistenceManager);
//        try{
//            this.context.setDecoder(new TransactionDecoderService(context.getClient().getCryptoSuite()));
//            dataPersistenceManager.saveContractInfo();
//        }catch (Exception e) {
//            log.error("save Contract Info, {}", e.getMessage());
//        }
        log.info("PrepareTaskJob<--->ExportConstant.getCurrentContext():{}",ExportConstant.getCurrentContext());
        ExportConstant.setCurrentContext(context);
        log.info("PrepareTaskJob<--->ExportConstant.getCurrentContext():{}",ExportConstant.getCurrentContext());
        try {
            buildClient();
        } catch (MalformedURLException e) {
            e.printStackTrace();
        } catch (ConfigException e) {
            e.printStackTrace();
        }
        mapsInfo = ContractParser.initContractMaps(context.getConfig().getContractInfoList());

//        DataPersistenceManager.setCurrentManager(dataPersistenceManager);
        ContractConstants.setCurrentContractMaps(mapsInfo);
        dataPersistenceManager.buildDataStore();
        try{
            this.context.setDecoder(new TransactionDecoderService(context.getClient().getCryptoSuite()));
            dataPersistenceManager.saveContractInfo();
        }catch (Exception e) {
            log.error("save Contract Info, {}", e.getMessage());
        }
    }

**Comment by wangyue168git** [comment]
您好，感谢反馈，方便提交下pr，看下吗

**Comment by wangyue168git** [comment]
#52
