### ISSUE TITLE
无法匹配到合约

### ISSUE THREAD

**Issue by saiwg** [WeBankBlockchain/Data-Export#53]
com.webank.blockchain.data.export.parser.service.ContractConstructorService
getConstructorNameByCode(String code)最后
```
    if (StringUtils.containsIgnoreCase(key, code)) {
        return entry;
    }
```
这里code是带0x的所以无法匹配到，应该改成
```
    if (StringUtils.containsIgnoreCase(key, code.substring(2))) {
        return entry;
    }
```

**Comment by dalaocu** [comment]
请问你的底层节点的版本是哪个？合约的版本是多少？

**Comment by saiwg** [comment]
> 请问你的底层节点的版本是哪个？合约的版本是多少？

节点是2.8.0，合约编译是用truffle编译的，版本显示是 - solc: 0.5.16+commit.9c3226ce.Emscripten.clang

**Comment by dalaocu** [comment]
> > 请问你的底层节点的版本是哪个？合约的版本是多少？
> 
> 节点是2.8.0，合约编译是用truffle编译的，版本显示是 - solc: 0.5.16+commit.9c3226ce.Emscripten.clang

合约编译器需要使用fisco bcos生态的编译器，不支持直接使用公链的编译器。

如可使用控制台的编译器： https://fisco-bcos-documentation.readthedocs.io/zh_CN/latest/docs/console/console_of_java_sdk.html#id3

**Comment by saiwg** [comment]
> > > 请问你的底层节点的版本是哪个？合约的版本是多少？
> > 
> > 
> > 节点是2.8.0，合约编译是用truffle编译的，版本显示是 - solc: 0.5.16+commit.9c3226ce.Emscripten.clang
> 
> 合约编译器需要使用fisco bcos生态的编译器，不支持直接使用公链的编译器。
> 
> 如可使用控制台的编译器： https://fisco-bcos-documentation.readthedocs.io/zh_CN/latest/docs/console/console_of_java_sdk.html#id3

好的，我用fisco生态的编译器试试
不过这个地方代码逻辑还是有问题的
![image](https://user-images.githubusercontent.com/28381005/164645097-59c1ac32-b194-419e-88c4-65a90e2f7551.png)

**Comment by saiwg** [comment]
好的，谢谢
