### ISSUE TITLE
具体的event表没有indexed修饰的字段和logIndex字段

### ISSUE THREAD

**Issue by saiwg** [WeBankBlockchain/Data-Export#54]
1. 如果导出没有indexed修饰的字段，那如何筛选？
com.webank.blockchain.data.export.parser.contract.EventParser.parseToInfoList()
```
for (NamedType namedType : fields) {
    if (namedType.isIndexed()) {
        continue;
    }
.....
}
```
2. 没有logIndex字段，tx_hash无法作为唯一键，一个交易中可能触发了多次相同的事件

**Comment by dalaocu** [comment]
> 1. 如果导出没有indexed修饰的字段，那如何筛选？
>    com.webank.blockchain.data.export.parser.contract.EventParser.parseToInfoList()
> 
> ```
> for (NamedType namedType : fields) {
>     if (namedType.isIndexed()) {
>         continue;
>     }
> .....
> }
> ```
> 
> 2. 没有logIndex字段，tx_hash无法作为唯一键，一个交易中可能触发了多次相同的事件

1. 所有非indexed修饰的字段都会被正常导出。
2. 数据导出是从tx_receipt中导出，不会触发多个相同的事件。

**Comment by saiwg** [comment]
1. 没有indexed修饰的字段，无法对event进行筛选。我理解写合约的时候就不要加indexed就可以了，但是如果是已经部署在用的合约，已经加了indexed怎么处理呢？
2. 比如ERC20，一个交易中给同一个地址B转两次相同数量的TOKEN，tx_receipt就会有两个Transfer事件
Transfer(A, B, 100)
Transfer(A, B, 100)
这两条记录是一摸一样的，包括区块号，交易hash，因为它们在同一个交易中

**Comment by dalaocu** [comment]
> 

1、数据导出会导出所有的event到db中。另外，java sdk支持对indexed字段的解析，可以通过sdk来解析indexed修饰的字段。
2、如果需要筛选，需要在合约中自己定义特征值。比如，在上面的例子中，添加一个id或sequence字段。但在上述这个例子中，如果一个函数调用触发了多个事件，数据导出会如实导出所有产生的事件。
