### ISSUE TITLE
ExportExecutor任务没有捕获Error，会导致同步任务失败很难找到原因

### ISSUE THREAD

**Issue by chzcb** [WeBankBlockchain/Data-Export#63]
文件 com.webank.blockchain.data.export.task.DataExportExecutor.java 里面
`    
class ExportExecutor implements Runnable {

        @Override
        public void run() {
            ExportConstant.setCurrentContext(context);
            DataPersistenceManager.setCurrentManager(DataPersistenceManager.create(context));
            try {
                crawlRunner.export();
            } catch (Exception e) { //TODO 这里改成捕获Throwable，否则任务失败了没有报错提示
                log.error("DataExportExecutor boot failed ", e);
            }
        }
    }
`
在使用过程中，因为hu-tools版本过低，有漏洞，所以升级了版本后，发现export任务启动后就中断，Debug之后，发现抛了NoSuchMethodError。
建议：
1. 后续版本升级hu-tools的版本
2. 捕获异常为Throwable

**Comment by wangyue168git** [comment]
很好的建议，可以提个PR吗

**Comment by chzcb** [comment]
这个改动太小了啊，你可以顺手改了。
目前有项目在用，比如交易量统计这个只统计最后一天就不太好用，因为历史同步可能会出错然后跳过。
等后面有时间可以一起优化再提交。
