### ISSUE TITLE
事件数据存储模型的疑问

### ISSUE THREAD

**Issue by meilongwhpu** [WeBankBlockchain/Data-Export#9]
合约中的事件定义如下：
event Transfer(address indexed from, address indexed to, uint256 value);
在该事件数据存储模型中，只有_value字段，另外两个address类型的参数from和to没有创建相应的字段，请问这个是什么原因导致的呢？

**Comment by wangyue168git** [comment]
去掉indexed就可以。
索引参数本身不会被保存。你只能搜索它们的值（来确定相应的日志数据是否存在），而不能获取它们的值本身。
参照：[indexed](https://solidity-cn.readthedocs.io/zh/develop/contracts.html?highlight=indexed)
